version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Build Project
          command: mvn -B -DskipTests clean package
      - run:
          name: Run Tests and Collect Coverage
          command: mvn verify
      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report
      - run:
          name: Check for Jacoco Report File
          command: |
              echo "Checking for Jacoco report in target/site/jacoco/"
              ls target/site/jacoco/
              if [ -f target/site/jacoco/jacoco.xml ]; then
                echo "Jacoco report found!"
                cat target/site/jacoco/jacoco.xml | head -n 20
              else
                echo "Jacoco report not found in target/site/jacoco/"
                exit 1
              fi
      - run:
          name: Display Jacoco XML Report
          command: |
            cat target/site/jacoco/jacoco.xml | head -n 20



  upload-codecov:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Upload Coverage to Codecov
          command: |
              echo "Uploading Jacoco report to Codecov"
              ls target/site/jacoco/
              bash <(curl -s https://codecov.io/bash) -f target/site/jacoco/jacoco.xml -t $CODECOV_TOKEN -F
            

workflows:
  upload-to-codecov:
    jobs:
      - build-and-test
      - upload-codecov:
          requires:
            - build-and-test
