version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Build Project
          command: mvn -B -DskipTests clean package
      - run:
          name: Run Tests and Collect Coverage
          command: mvn verify
      - run:
          name: List Target Directory After Verification
          command: ls -R target
      - run:
          name: Generate Coverage Report
          command: |
            mvn jacoco:report
            echo "Listing target/site directory after report generation:"
            ls -R target/site
      - run:
          name: Display Working Directory and Content
          command: |
            echo "Répertoire courant : $(pwd)"
            ls -R
      - run:
          name: List Target Directory After Jacoco Report
          command: ls -R target
      - run:
          name: Check for Jacoco Report File
          command: |
            echo "Checking for Jacoco report in target/site/jacoco/"
            ls target/site/jacoco/
            if [ -f target/site/jacoco/jacoco.xml ]; then
              echo "Jacoco report found!"
              cat target/site/jacoco/jacoco.xml | head -n 20
            else
              echo "Jacoco report not found in target/site/jacoco/"
              exit 1
            fi
      - run:
          name: Vérifier le contenu de Jacoco avant l'upload
          command: |
            echo "Vérification du contenu de target/site/jacoco/"
            ls -l target/site/jacoco/
            cat target/site/jacoco/jacoco.xml
      - run:
          name: Display Jacoco XML Report
          command: |
            cat target/site/jacoco/jacoco.xml | head -n 20
    
    

  upload-codecov:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Upload Coverage to Codecov
          command: |
            echo "Uploading Jacoco report to Codecov without age check"
            bash <(curl -s https://codecov.io/bash) -f target/site/jacoco/jacoco.xml -t $CODECOV_TOKEN -X age -v
    

workflows:
  upload-to-codecov:
    jobs:
      - build-and-test
      - upload-codecov:
          requires:
            - build-and-test
