version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:21-jdk  # Utilise l'image OpenJDK 8 pour la compilation et les tests
    steps:
      - checkout  # Récupère le code source
      - run:
          name: Run Maven Tests
          command: mvn clean test
      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report
      - codecov/upload:  # Utilise l'orbe Codecov pour uploader les résultats
          file: target/site/jacoco/jacoco.xml  # Spécifie le rapport JaCoCo généré
          token: CODECOV_TOKEN
      - run:
          name: Generate JavaDoc
          command: mvn javadoc:javadoc
      - run:
          name: List JaCoCo Report Directory
          command: ls -la target/site/jacoco

  docs-deploy:
    docker:
      - image: circleci/node:8.10.0  # Utilise Node.js pour le déploiement sur GitHub Pages
    steps:
      - checkout
      - attach_workspace:
          at: /workspace  # Attache le workspace pour accéder aux fichiers générés
      - run:
          name: Install gh-pages Dependency
          command: |
            npm install -g gh-pages@2.0.1
            git config user.email "hafsaabou2@gmail.com"
            git config user.name "HafsaAbouyassine"
      - add_ssh_keys:
          fingerprints:
            - "SHA256:CmuXAAUOtBw24KObf1iu6KIBh0bTsO5iMyepBRflALg"  # Remplacez par votre fingerprint SSH
      - run:
          name: Deploy Documentation to GitHub Pages
          command: gh-pages --dist target/site/apidocs/  # Déploie la JavaDoc générée

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master  # Exécute le build seulement sur la branche master
      - docs-deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
