version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Set Up Environment
          command: |
            sudo apt update
            sudo apt install -y python3-pip
            pip3 install -r requirements.txt
      - run:
          name: Run Tests and Collect Coverage
          command: mvn test
      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report

  upload-codecov:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Upload Coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
        # Ajoutez un chemin de rapport si nécessaire
        # command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -f target/site/jacoco/jacoco.xml

workflows:
  upload-to-codecov:
    jobs:
      - build-and-test
      - upload-codecov:
          requires:
            - build-and-test
