version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Build Project
          command: mvn -B -DskipTests clean package
      - run:
          name: Run Tests and Collect Coverage
          command: mvn verify
      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report
      - run:
          name: Upload Coverage to Codecov
          command: |
            echo "Uploading Jacoco report to Codecov"
            bash <(curl -s https://codecov.io/bash) -f target/site/jacoco/jacoco.xml -t $CODECOV_TOKEN -X verbose
            echo "Upload terminé"
      #Javadoc
      - run:
          name: Generate Javadoc
          command: |
            mvn javadoc:javadoc

      # Deployment
      - add_ssh_keys:
          fingerprints:
            - "SHA256:/CZUIgiVzYyt3i1DPw+5NTtvDwNkXeRyUOB37DFXTOQ"

      - run:
          name: Debug SSH Key Path
          command: ls -la ~/.ssh



      - run:
          name: Install and configure gh-pages
          command: |
            git config --global user.email "ci-build@HafsaAbouyassine.com"
            git config --global user.name "ci-build"

            git clone git@github.com:${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git gh-pages
            cd gh-pages && git checkout -b gh-pages        
            cp -r target/site/apidocs/* ./
            
            git add -A
            git commit -m "[skip ci] Updated Javadoc"
            git push origin gh-pages --force 


workflows:
  build-and-upload:
    jobs:
      - build-and-test
