version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Build Project
          command: mvn -B -DskipTests clean package
      - run:
          name: Run Tests and Collect Coverage
          command: mvn verify
      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report
      - run:
          name: Upload Coverage to Codecov
          command: |
            echo "Uploading Jacoco report to Codecov"
            bash <(curl -s https://codecov.io/bash) -f target/site/jacoco/jacoco.xml -t $CODECOV_TOKEN -X verbose
            echo "Upload terminé"
      #Javadoc
      - run:
          name: Generate Javadoc
          command: |
            mvn javadoc:javadoc


workflows:
  build-and-upload:
    jobs:
      - build-and-test
